import LegalPageLayout from '@/components/Legal/LegalPageLayout';

export default function PrivacyPolicy() {
  return (
    <LegalPageLayout title="Privacy Policy" lastUpdated="May 25, 2026">
      <div className="space-y-8 text-gray-700 dark:text-gray-300">
        <section>
          <p className="text-sm text-gray-500 dark:text-gray-400 mb-4">
            <strong>IMPORTANT:</strong> This Privacy Policy is provided for informational purposes. It reflects our commitment to data protection under the EU General Data Protection Regulation (GDPR) and Italian privacy laws. For legal advice specific to your situation, please consult a qualified privacy professional.
          </p>
          <p>
            This Privacy Policy describes how <strong>Giovanni de Caprio</strong> ("we", "us", "our"), operating as a sole proprietorship (Ditta Individuale) under Italian law, collects, uses, stores, and protects your personal data when you use the Morpheus website and services (collectively, the "Service").
          </p>
          <p>
            We are committed to protecting your privacy and ensuring that your personal data is handled in a safe and responsible manner, in compliance with the EU General Data Protection Regulation (Regulation EU 2016/679 — "GDPR") and the Italian Legislative Decree no. 196/2003 as amended by Legislative Decree no. 101/2018 ("Privacy Code").
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">1. Data Controller</h2>
          <p>The Data Controller responsible for your personal data is:</p>
          <div className="bg-gray-50 dark:bg-slate-800/50 p-4 rounded-lg mt-2 text-sm">
            <p><strong>Giovanni de Caprio</strong></p>
            <p>Ditta Individuale</p>
            <p>Via Gaspare Gozzi 113</p>
            <p>00145 Roma (RM), Italy</p>
            <p>C.F.: DCPGNN04P28H501W</p>
            <p>P.IVA: 18340151002</p>
            <p>Email: hello@morpheusink.com</p>
          </div>
          <p className="mt-3">
            You can contact us regarding data protection matters at the email address above. We have not appointed a Data Protection Officer (DPO) as we do not meet the thresholds requiring one under Article 37 GDPR.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">2. What Data We Collect</h2>
          <p>We collect and process the following categories of personal data:</p>
          <h3 className="font-semibold text-gray-900 dark:text-white mt-3 mb-2">2.1 Account Information</h3>
          <ul className="list-disc pl-5 space-y-1">
            <li>Email address</li>
            <li>Name (if provided)</li>
            <li>Account credentials (passwords are hashed and never stored in plain text)</li>
            <li>User ID generated by our authentication system</li>
          </ul>
          <h3 className="font-semibold text-gray-900 dark:text-white mt-3 mb-2">2.2 Content You Create</h3>
          <ul className="list-disc pl-5 space-y-1">
            <li>Books, chapters, and story content</li>
            <li>Character profiles and world-building notes</li>
            <li>Chat messages and prompts sent to the AI assistant</li>
            <li>Lore bible entries and other creative materials</li>
          </ul>
          <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
            <strong>Important:</strong> Your creative content belongs to you. We do not use your writing to train AI models. See Section 9 for details on our AI data practices.
          </p>
          <h3 className="font-semibold text-gray-900 dark:text-white mt-3 mb-2">2.3 Usage and Technical Data</h3>
          <ul className="list-disc pl-5 space-y-1">
            <li>IP address (logged for security purposes)</li>
            <li>Browser type and version</li>
            <li>Device information</li>
            <li>Session tokens and authentication logs</li>
            <li>Error logs and diagnostic information</li>
          </ul>
          <h3 className="font-semibold text-gray-900 dark:text-white mt-3 mb-2">2.4 Payment Information</h3>
          <ul className="list-disc pl-5 space-y-1">
            <li>We do not store credit card details. Payment processing is handled by LemonSqueezy, our payment processor.</li>
            <li>We receive transaction IDs, subscription status, and billing history from LemonSqueezy.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">3. Legal Basis for Processing</h2>
          <p>Under GDPR Article 6, we process your personal data based on the following legal grounds:</p>
          <table className="w-full text-sm mt-3 border-collapse">
            <thead>
              <tr className="border-b border-gray-200 dark:border-slate-700">
                <th className="text-left py-2 pr-4 font-semibold text-gray-900 dark:text-white">Processing Activity</th>
                <th className="text-left py-2 pr-4 font-semibold text-gray-900 dark:text-white">Legal Basis</th>
              </tr>
            </thead>
            <tbody className="text-gray-600 dark:text-gray-400">
              <tr className="border-b border-gray-100 dark:border-slate-800">
                <td className="py-2 pr-4">Account registration and authentication</td>
                <td className="py-2 pr-4">Contract (Art. 6(1)(b))</td>
              </tr>
              <tr className="border-b border-gray-100 dark:border-slate-800">
                <td className="py-2 pr-4">Providing the writing and AI assistance service</td>
                <td className="py-2 pr-4">Contract (Art. 6(1)(b))</td>
              </tr>
              <tr className="border-b border-gray-100 dark:border-slate-800">
                <td className="py-2 pr-4">Payment processing and billing</td>
                <td className="py-2 pr-4">Contract (Art. 6(1)(b))</td>
              </tr>
              <tr className="border-b border-gray-100 dark:border-slate-800">
                <td className="py-2 pr-4">Security, fraud prevention, and error debugging</td>
                <td className="py-2 pr-4">Legitimate interest (Art. 6(1)(f))</td>
              </tr>
              <tr className="border-b border-gray-100 dark:border-slate-800">
                <td className="py-2 pr-4">Analytics and service improvement</td>
                <td className="py-2 pr-4">Consent (Art. 6(1)(a))</td>
              </tr>
              <tr className="border-b border-gray-100 dark:border-slate-800">
                <td className="py-2 pr-4">Marketing communications</td>
                <td className="py-2 pr-4">Consent (Art. 6(1)(a))</td>
              </tr>
              <tr>
                <td className="py-2 pr-4">Legal compliance and tax obligations</td>
                <td className="py-2 pr-4">Legal obligation (Art. 6(1)(c))</td>
              </tr>
            </tbody>
          </table>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">4. How We Use Your Data</h2>
          <p>We use your personal data for the following purposes:</p>
          <ul className="list-disc pl-5 space-y-1 mt-2">
            <li><strong>To provide the Service:</strong> Authenticate you, store your content, and enable AI-powered writing assistance.</li>
            <li><strong>To process payments:</strong> Manage subscriptions and billing through our payment processor.</li>
            <li><strong>To ensure security:</strong> Protect against unauthorized access, fraud, and abuse.</li>
            <li><strong>To improve the Service:</strong> Analyze usage patterns (only with your consent) to enhance features and fix bugs.</li>
            <li><strong>To communicate with you:</strong> Send service-related notifications, respond to support requests, and (with consent) marketing emails.</li>
            <li><strong>To comply with legal obligations:</strong> Meet tax, accounting, and regulatory requirements under Italian and EU law.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">5. Data Retention</h2>
          <p>We retain your personal data only for as long as necessary to fulfill the purposes for which it was collected:</p>
          <ul className="list-disc pl-5 space-y-1 mt-2">
            <li><strong>Account and content data:</strong> Retained until you delete your account or request data deletion. After account deletion, content is permanently removed from active systems within 30 days.</li>
            <li><strong>Authentication logs:</strong> Retained for 90 days for security purposes.</li>
            <li><strong>Error logs:</strong> Retained for 30 days.</li>
            <li><strong>Payment and billing records:</strong> Retained for 10 years as required by Italian tax law (DPR 600/1973 and subsequent amendments).</li>
            <li><strong>Cookie consent records:</strong> Retained for 12 months or until you update your preferences.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">6. Data Sharing and Sub-processors</h2>
          <p>We do not sell your personal data. We share data only with trusted third-party service providers (sub-processors) who help us operate the Service:</p>
          <table className="w-full text-sm mt-3 border-collapse">
            <thead>
              <tr className="border-b border-gray-200 dark:border-slate-700">
                <th className="text-left py-2 pr-4 font-semibold text-gray-900 dark:text-white">Sub-processor</th>
                <th className="text-left py-2 pr-4 font-semibold text-gray-900 dark:text-white">Purpose</th>
                <th className="text-left py-2 pr-4 font-semibold text-gray-900 dark:text-white">Location</th>
              </tr>
            </thead>
            <tbody className="text-gray-600 dark:text-gray-400">
              <tr className="border-b border-gray-100 dark:border-slate-800">
                <td className="py-2 pr-4">Appwrite Cloud</td>
                <td className="py-2 pr-4">Database, authentication, file storage</td>
                <td className="py-2 pr-4">EU / Germany (FRA1)</td>
              </tr>
              <tr className="border-b border-gray-100 dark:border-slate-800">
                <td className="py-2 pr-4">OpenRouter</td>
                <td className="py-2 pr-4">AI model inference and LLM API routing</td>
                <td className="py-2 pr-4">United States</td>
              </tr>
              <tr className="border-b border-gray-100 dark:border-slate-800">
                <td className="py-2 pr-4">LemonSqueezy</td>
                <td className="py-2 pr-4">Payment processing and subscription management</td>
                <td className="py-2 pr-4">United States</td>
              </tr>
              <tr>
                <td className="py-2 pr-4">Google Analytics</td>
                <td className="py-2 pr-4">Website usage analytics (only with consent)</td>
                <td className="py-2 pr-4">United States</td>
              </tr>
            </tbody>
          </table>
          <p className="mt-3 text-sm text-gray-500 dark:text-gray-400">
            For transfers to non-EU countries (United States), we rely on Standard Contractual Clauses (SCCs) approved by the European Commission under GDPR Article 46(2)(c) to ensure an adequate level of data protection.
          </p>
          <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
            We have signed Data Processing Agreements (DPAs) with all sub-processors that handle personal data on our behalf, as required by GDPR Article 28.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">7. Your Rights Under GDPR</h2>
          <p>As a data subject under GDPR, you have the following rights:</p>
          <ul className="list-disc pl-5 space-y-2 mt-2">
            <li><strong>Right of access (Art. 15):</strong> You can request a copy of all personal data we hold about you.</li>
            <li><strong>Right to rectification (Art. 16):</strong> You can request correction of inaccurate or incomplete data.</li>
            <li><strong>Right to erasure / "Right to be forgotten" (Art. 17):</strong> You can request deletion of your personal data, subject to legal retention obligations.</li>
            <li><strong>Right to restrict processing (Art. 18):</strong> You can request that we limit how we use your data in certain circumstances.</li>
            <li><strong>Right to data portability (Art. 20):</strong> You can request your data in a structured, machine-readable format and transfer it to another service.</li>
            <li><strong>Right to object (Art. 21):</strong> You can object to processing based on legitimate interests or for direct marketing purposes.</li>
            <li><strong>Right to withdraw consent (Art. 7(3)):</strong> Where we rely on consent, you can withdraw it at any time without affecting the lawfulness of processing before withdrawal.</li>
            <li><strong>Right to lodge a complaint (Art. 77):</strong> You have the right to complain to the Italian Data Protection Authority (Garante per la Protezione dei Dati Personali) or your local supervisory authority.</li>
          </ul>
          <p className="mt-3">
            To exercise any of these rights, please contact us at <a href="mailto:hello@morpheusink.com" className="text-primary-600 dark:text-primary-400 underline">hello@morpheusink.com</a>. We will respond within 30 days of receiving your request. We may need to verify your identity before processing your request.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">8. Cookies and Similar Technologies</h2>
          <p>
            We use cookies and similar technologies to provide and secure our Service. For detailed information about the cookies we use, their purposes, and how to manage your preferences, please see our <a href="/cookies" className="text-primary-600 dark:text-primary-400 underline">Cookie Policy</a>.
          </p>
          <p className="mt-2">
            By using our Service, you consent to the use of essential cookies. For analytics and marketing cookies, we will request your explicit consent through our cookie banner before placing them.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">9. AI Data Practices</h2>
          <p>Given that Morpheus is an AI-powered writing assistant, we want to be transparent about how your data interacts with AI systems:</p>
          <ul className="list-disc pl-5 space-y-2 mt-2">
            <li><strong>Your content is yours:</strong> We do not use your books, chapters, characters, or creative writing to train, fine-tune, or improve any AI models.</li>
            <li><strong>Prompts are processed by third-party AI providers:</strong> When you use the AI chat feature, your prompts and context are sent to OpenRouter, which routes them to underlying language models (e.g., OpenAI, Anthropic, Google). We have verified that our primary AI providers have zero data retention policies for API calls, meaning your prompts are not stored or used for model training.</li>
            <li><strong>No automated decision-making:</strong> Morpheus does not make decisions about you that produce legal or similarly significant effects (GDPR Article 22).</li>
            <li><strong>EU AI Act:</strong> Morpheus qualifies as a "limited risk" AI system under the EU AI Act. We provide transparency about AI-generated outputs and do not deceive users about the artificial nature of the content.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">10. Data Security</h2>
          <p>We implement appropriate technical and organizational measures to protect your personal data:</p>
          <ul className="list-disc pl-5 space-y-1 mt-2">
            <li>Encryption of data in transit using TLS 1.2+ (HTTPS)</li>
            <li>Encryption of data at rest where supported by our infrastructure providers</li>
            <li>Secure authentication using industry-standard hashing algorithms (bcrypt)</li>
            <li>Role-based access controls and minimal data access principles</li>
            <li>Regular security reviews and dependency updates</li>
          </ul>
          <p className="mt-2">
            In the event of a personal data breach, we will notify the Italian Data Protection Authority (Garante) within 72 hours of becoming aware of the breach, where required by GDPR Article 33. If the breach is likely to result in a high risk to your rights and freedoms, we will also notify affected users without undue delay (GDPR Article 34).
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">11. Children's Privacy</h2>
          <p>
            The Service is not intended for children under 16 years of age. We do not knowingly collect personal data from children under 16. If we become aware that we have collected personal data from a child under 16 without verification of parental consent, we will take steps to delete that information. If you believe we might have information from or about a child under 16, please contact us.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">12. Changes to This Privacy Policy</h2>
          <p>
            We may update this Privacy Policy from time to time to reflect changes in our practices, legal requirements, or Service features. We will notify you of any material changes by posting the updated policy on this page with a revised "Last updated" date. We encourage you to review this Privacy Policy periodically.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">13. Contact Us</h2>
          <p>If you have any questions, concerns, or requests regarding this Privacy Policy or our data practices, please contact us:</p>
          <div className="bg-gray-50 dark:bg-slate-800/50 p-4 rounded-lg mt-2 text-sm">
            <p><strong>Giovanni de Caprio</strong></p>
            <p>Email: <a href="mailto:hello@morpheusink.com" className="text-primary-600 dark:text-primary-400 underline">hello@morpheusink.com</a></p>
            <p>Address: Via Gaspare Gozzi 113, 00145 Roma (RM), Italy</p>
            <p className="mt-2">You also have the right to lodge a complaint with the Italian Data Protection Authority:</p>
            <p><a href="https://www.garanteprivacy.it" target="_blank" rel="noopener noreferrer" className="text-primary-600 dark:text-primary-400 underline">www.garanteprivacy.it</a></p>
          </div>
        </section>
      </div>
    </LegalPageLayout>
  );
}
